### ISSUE TITLE
Investigate the creation of a homebrew core formula

### ISSUE THREAD

**Issue by leecalcote** [meshery/homebrew-tap#10]
Goreleaser is the package used to generate the `mesheryctl` homebrew tap. It has the following caveat (as seen on https://goreleaser.com/customization/homebrew/):

<img width="789" alt="Screen Shot 2020-06-09 at 12 03 40 PM" src="https://user-images.githubusercontent.com/7570704/84178006-58f4e380-aa49-11ea-8107-18010fd6af25.png">

Is there a workaround or alternative approach that we might take to removing the need for users to first add the layer5io/tap to their brew repo list?

**Comment by leecalcote** [comment]
@naturalett will you have a look at how `gh` (GitHub's cli) accomplishes getting the `gh` into homebrew core with goreleaser? https://github.com/cli/cli/blob/trunk/.github/workflows/releases.yml#L30

**Comment by nishantwrp** [comment]
> EDIT: I forgot to claim the issue but started working on it since no one was assigned. I hope that's fine.

Hi @leecalcote, I investigated this a bit and here's what I found.

**How `gh` handles it?**
`gh` doesn't use `goreleaser` directly to push formula to a homebrew tap. It is used only to build and create binaries. After that they use [this](https://github.com/mislav/bump-homebrew-formula-action) GitHub action to bump the version in their formula by creating a pull request to the `homebrew/homebrew-core` repository. (Ref - [.github/workflows/releases.yml](https://github.com/cli/cli/blob/6703677a951b04b6a10ec903133407d0fa1307bf/.github/workflows/releases.yml#L190), One of the pull requests - https://github.com/Homebrew/homebrew-core/pull/104209)

**Using a custom tap**
If the only reason to shift to `homebrew-core` is because the user needs to enter two commands to install `mesheryctl`, the user can still enter one command to install `brew install meshery/tap/mesheryctl`. (But I agree, `brew install mesheryctl` would be neater.)

Also, in this [page](https://meshery.io/service-mesh-management/meshery/getting-started) we've mentioned to add the tap using `brew tap meshery/tap`. Shouldn't it be changed to `meshery/tap`?

**Comment by leecalcote** [comment]
@nishantwrp thanks! Good research. Yes, assuming no hiccups to existing users, it should change to `meshery/tap`. 

Yes, We want for mesheryctl to be as discoverable and as intuitive to install as possible and are willing to go to great lengths to make it so. Do you think you would be successful in moving us to the same GitHub action?

**Comment by leecalcote** [comment]
> EDIT: Sounds real good. I appreciate your diligence in research and write up.

**Comment by nishantwrp** [comment]
>  Yes, assuming no hiccups to existing users, it should change to meshery/tap.

Yes, I don't think there will be any problem to existing users. We already mention `meshery/tap` at some places like: https://meshery.io. Should I make pull requests to update it in remaining places too?

> Do you think you would be successful in moving us to the same GitHub action?

Yup, I think we can add mesheryctl to homebrew-core. But I just want to give a heads up that, the formula added to `homebrew-core` should build the binary from source. We can't provide pre-built binaries to that formula. (Ref - https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae). 

We can still keep the binaries built by goreleaser as artifacts in GitHub releases. It's just that they'll be no use to the homebrew formula. `gh` also has a [script](https://github.com/cli/cli/blob/trunk/script/build.go) for building the cli in their [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gh.rb#L31). We probably won't need a separate script for building `mesheryctl`, simply using `go build` with necessary flags in the formula file should suffice. (Similar to - [ahoy.rb](https://github.com/Homebrew/homebrew-core/blob/00ee3fef3f9e178d31f735793bb5b1e84dd23ffd/Formula/ahoy.rb#L23))

cc @leecalcote

**Comment by leecalcote** [comment]
> Yes, I don't think there will be any problem to existing users. We already mention meshery/tap at some places like: https://meshery.io/. Should I make pull requests to update it in remaining places too?

I hope so, although, it'd good to have this confirmed. Existing users who have installed the meshery/tap might find their upgrade process broken. I wonder where you might dig up evidence to prove (or suggest) smooth sailing. Yes, this switch is ideal. Please investigate.

**Comment by leecalcote** [comment]
Great notes on the requirement to build from source, @nishantwrp 👍

We do need the built binaries deposited as artifacts in the `meshery/meshery` releases, but should have no issue with a separate build (at the same git tag - initiated from the same workflow trigger event as a Meshery release). Ideally, we're able to reuse the existing build process and avoid both additional time developing, debugging and then future time maintaining a separate workflow - https://github.com/meshery/meshery/blob/37899577a6a388d23a9d759c691ed620abd9b643/.github/workflows/build-and-release-stable.yml#L42

Please do proceed here. There are regular Meshery development and CI meetings that you're encouraged to engage within, too - https://meshery.io/calendar.

**Comment by leecalcote** [comment]
@nishantwrp let's put this topic as an agenda item in next week's [Meshery Development Meeting](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit). You can demo progress. Will that work?

**Comment by nishantwrp** [comment]
@leecalcote yup that works!

**Comment by nishantwrp** [comment]
An update on this issue. I was able to create a valid homebrew-core formula which successfully builds meshery. It also passed the `brew audit` checks. I'd like the community to take a look on the formula, and suggest any improvements. 

```ruby
class Mesheryctl < Formula
  desc "The Cloud Native Management Plane."
  homepage "https://meshery.io"
  url "https://github.com/meshery/meshery.git",
    tag: "v0.6.0-rc.6a",
    revision: "201ac20cd4c86568bffe14b4d0b3bcf7a3e1168b"
  version "0.6.0-rc.6a"
  license "Apache-2.0"
  head "https://github.com/meshery/meshery.git", branch: "master"

  depends_on "go" => :build

  def install
    ENV["CGO_ENABLED"] = "0"

    ldflags = %W[
      -s -w
      -X github.com/meshery/meshery/mesheryctl/internal/cli/root/constants.version=v#{version}
      -X github.com/meshery/meshery/mesheryctl/internal/cli/root/constants.commitsha=#{Utils.git_short_head}
      -X github.com/meshery/meshery/mesheryctl/internal/cli/root/constants.releasechannel=stable
    ]

    system "go", "build", *std_go_args(ldflags: ldflags), "./mesheryctl/cmd/mesheryctl"
  end

  test do
    # We need a 'y' here because mesheryctl needs a meshery config file to display version
    # of the server along with the cli. Since it doesn't exist yet it shows a prompt if the user
    # wants to create a default config file.
    assert_match version.to_s, shell_output("#{bin}/mesheryctl version <<< y 2>&1")
  end
end
```

After this, we can make a pull request to the official `homebrew-core` repository. While that pull request gets reviewed, we need modify our [stable release workflow](https://github.com/meshery/meshery/blob/master/.github/workflows/build-and-release-stable.yml#L41) to include [this](https://github.com/marketplace/actions/bump-homebrew-formula) GitHub action which will automatically make a pull request to the `homebrew-core` repo updating the formula.

We still need to figure out whether we will continue supporting our [custom tap](https://github.com/meshery/homebrew-tap) (cc: @leecalcote). I've not yet researched on whether the users that have installed `mesheryctl` via our tap will be able to receive updates from the official tap.

**Comment by nishantwrp** [comment]
Just found about that homebrew supports migration b/w taps. (Ref - [SO](https://stackoverflow.com/a/70089144/13135203)). We won't need to push releases from `stable` channel to this repository. We can just update the formula in `homebrew-core` repository. Also, existing users will be able to upgrade `mesheryctl` without any issues.

**Comment by nishantwrp** [comment]
Created a pull request on homebrew-core: https://github.com/Homebrew/homebrew-core/pull/105761
