### ISSUE TITLE
mesheryctl available as a bottle?

### ISSUE THREAD

**Issue by leecalcote** [meshery/homebrew-tap#12]
It would be nice to track the number of downloads (installations?) of `mesheryctl`. Does use of https://bintray.com/homebrew/bottles make this possible?

**Comment by Jashpatel1** [comment]
Yes, the stats regarding no. of downloads are provided as you can see here [download stats by JFrog](https://www.jfrog.com/confluence/display/BT/Statistics)

**Comment by leecalcote** [comment]
Which begs the next question as to whether we can use goreleaser to produce a bottle. Or maybe just a core tap (https://github.com/meshery/homebrew-tap/issues/10) like the way [`gh` uses goreleaser](https://github.com/cli/cli) to produce a core tap.

**Comment by Jashpatel1** [comment]
@leecalcote I dont have much knowledge regarding Go. I might not be the perfect one to answer.

**Comment by leecalcote** [comment]
Ok, no sweat, @Jashpatel1. I appreciate you jumping into help advance the conversation / investigation.
