### ISSUE TITLE
Setting up builds for Darwin arm64 (Apple Silicon M1)

### ISSUE THREAD

**Issue by EmperorYP7** [meshery/homebrew-tap#16]
Here's the output for `brew tap layer5io/tap`

<img width="935" alt="Screenshot 2021-03-12 at 10 15 18 PM" src="https://user-images.githubusercontent.com/62606998/110971107-75c79a00-8380-11eb-96b1-da2d768f7116.png">

OS: Darwin arm64 20.3.0
Homebrew version: v3.0.5 (for arm64)

I know this is dependent on the development of GitHub Actions for the new architecture, but this shall keep track of it for once it is feasible.

**Comment by leecalcote** [comment]
Thanks, @EmperorYP7. 

@warunicorn19, are we good to close this issue? I believe this has been completed.

**Comment by warunicorn19** [comment]
Yes @leecalcote , this issue can be closed 🙂.
