### ISSUE TITLE
[README] Fix broken documentation link

### ISSUE THREAD

**Issue by josephmidura** [meshery/homebrew-tap#21]
The link to Meshery documentation at the bottom of the screen is broken.

The correct link is [here](https://docs.meshery.io/guides/mesheryctl).

![Screen Shot 2021-07-31 at 2 24 56 PM](https://user-images.githubusercontent.com/11523557/127750539-db12567a-e334-43e6-be6d-92f1e840ffef.png)

**Comment by siddhantprateek** [comment]
i have fixed the link

**Comment by leecalcote** [comment]
Thank you, @josephmidura, @siddhantprateek, @warunicorn19
