### ISSUE TITLE
Update readme with standard Meshery Readme content

### ISSUE THREAD

**Issue by leecalcote** [meshery/homebrew-tap#30]

**Comment by lodenrogue** [comment]
Do you mean making the README looks like https://docs.meshery.io/installation/mesheryctl overview page?

**Comment by leecalcote** [comment]
Thanks for asking. No, rather to take the templated portions of any of the ‘meshery’ GitHub org’s readme.md’s in order to refresh this repo’s readme.md.

**Comment by manikmmalhotra** [comment]
can i work on this one @leecalcote, from what i've analyzed we have to create a readme similar to other projects of meshery as mentioned

**Comment by leecalcote** [comment]
Thanks. Yes, that's right.
