### ISSUE TITLE
Update readme to reflect that this tap is deprecated

### ISSUE THREAD

**Issue by nishantwrp** [meshery/homebrew-tap#33]
We've recently migrated `mesheryctl` releases from our custom [meshery/tap](https://github.com/meshery/homebrew-tap) to the official [homebrew/core](https://github.com/Homebrew/homebrew-core). This repositories should be updated to reflect that this tap is deprecated and users should directly install `mesheryctl` using `brew install mesheryctl`.

**Comment by prak30** [comment]
hey can i work on this one?

**Comment by nishantwrp** [comment]
Go ahead @prak30!

**Comment by prak30** [comment]
hi @nishantwrp how should I go about, should I update the readme directly to 
We've recently migrated mesheryctl releases from our custom [meshery/tap](https://github.com/meshery/homebrew-tap) to the official [homebrew/core](https://github.com/Homebrew/homebrew-core). This repositories should be updated to reflect that this tap is deprecated and users should directly install mesheryctl using brew install mesheryctl.
??

**Comment by prak30** [comment]
I have created PR can you check it https://github.com/prak30/homebrew-tap/pull/1
@nishantwrp

**Comment by prak30** [comment]
And the rest of the readme should I just remove all the lines? @nishantwrp

**Comment by prak30** [comment]
I have made the changes here https://github.com/prak30/homebrew-tap/pull/2 you can review and merge it @nishantwrp

**Comment by prak30** [comment]
sorry @nishantwrp had made the changes on github ui. I am used to the command line . Check this https://github.com/meshery/homebrew-tap/pull/35
