### ISSUE TITLE
Investigate shortening of installation commands

### ISSUE THREAD

**Issue by leecalcote** [meshery/homebrew-tap#9]
Can we reduce the number of commands that users who are installing `mesheryctl` have to run?  Can the installation instructions change from having users execute two commands to one command? It would be good to investigate whether the current installation commands:

```
brew tap layer5io/tap
brew install mesheryctl
```
can be shortened to:

```
brew install layer5io/mesheryctl
```

**Comment by glassxer1** [comment]
Hi, I am new to the community and would like to take this issue. Best

**Comment by leecalcote** [comment]
Hi @glassxer1, thank you. That would be great. 👍

**Comment by StarTrooper08** [comment]
Can I work on this issue?
If no one is working on this issue!

**Comment by leecalcote** [comment]
@StarTrooper08 yes, please do.
